# docker-compose.yml

version: '3.8'

services:
  # サービス1: MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001" # WebSocket用ポート
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - future_platform

  # サービス2: MinIO (オブジェクトストレージ)
  minio:
    image: minio/minio:latest
    container_name: minio-storage
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9090:9090" # WebUIポート
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data
    networks:
      - future_platform
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # サービス3: GStreamer録画コンテナ
  gstreamer-recorder:
    build: ./gstreamer-recorder
    container_name: gstreamer-recorder
    restart: unless-stopped
    depends_on:
      - minio
    ports:
      # 4台のカメラを想定し、ポート5000から5003までを公開
      - "5000-5003:5000-5003/udp"
    networks:
      - future_platform

# Dockerネットワークの定義
networks:
  future_platform:
    driver: bridge

# Dockerが管理するボリュームの定義
volumes:
  mosquitto-data:
  mosquitto-log:
  minio-data: